name: gigachat_dart
description: Dart client for GigaChat API
version: 0.1.0
repository: https://github.com/pwrshi/gigachat_dart

topics:
  - ai
  - nlp
  - llms
  - gigachat

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  fetch_client: ^1.1.1
  freezed_annotation: ^2.4.1
  http: ^1.2.1
  json_annotation: ^4.9.0
  meta: ^1.14.0
  openapi_generator_annotations: ^5.0.2
  uuid: ^4.4.0
dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  openapi_generator: ^5.0.2
  openapi_spec:
    git:
      url: https://github.com/tazatechnology/openapi_spec.git
      ref: 815b1cba74ef4519e36af02b78d237fffedc186d
  test: ^1.25.2
  very_good_analysis: 5.1.0
