name: gigachat_dart
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none


topics:
  - ai
  - nlp
  - llms
  - gigachat



environment:
  sdk: "^3.3.0"



dependencies:
  fetch_client: ^1.0.2
  freezed_annotation: ^2.4.1
  http: ^1.1.0
  json_annotation: ^4.8.1
  meta: ^1.11.0

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  #  openapi_spec: ^0.7.8
  openapi_spec:
    git:
      url: https://github.com/davidmigloz/openapi_spec.git
      ref: e14c0adaac69e9482e9b57f68fc7964032cdd44c
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0
